package com.bppl.SACCR_Reporting.repository;


import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

// tables required
import com.bppl.SACCR_Reporting.model.CR10;

public interface CR10Repository extends CrudRepository<CR10, Integer>{
	
	// All queries required to get aggregate values that are to be put into reports

	//CR1
	//1a
	@Query("select sum(EOP_BALANCE_AMT) from CR10  where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME') and ACCT_PASTDUE_FLAG = 'Y'")
	Double LoansDefaultedExposure();
	
	//1b
	@Query("select sum(EOP_BALANCE_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME') and ACCT_PASTDUE_FLAG = 'N'")
	Double LoansNotDefaultedExposure();
	
	//1c
	@Query("select (sum(TOT_WRITE_OFF_AMT) + sum(COLLECTIVE_PROVISION_AMT) + sum(SPECIFIC_PROVISION_AMT) + sum(OTH_PROVISION_AMT)) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME')")
	Double LoansAllowances();
	
	//1d
	@Query("select sum(SPECIFIC_PROVISION_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME')")
	Double LoansAllocatedSpecific();
	
	//1e
	@Query("select (sum(TOT_WRITE_OFF_AMT) + sum(COLLECTIVE_PROVISION_AMT) + sum(OTH_PROVISION_AMT)) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME')")
	Double LoansAllocatedGeneral();
	
	//2a
	@Query("select sum(EOP_BALANCE_AMT) from CR10 where STD_PRODUCT_TYPE_CD = 'BOND' and ACCT_PASTDUE_FLAG = 'Y'")
	Double DebtDefalutedExposure();
		
	//2b
	@Query("select sum(EOP_BALANCE_AMT) from CR10 where STD_PRODUCT_TYPE_CD = 'BOND' and ACCT_PASTDUE_FLAG = 'N'")
	Double DebtNotDefalutedExposure();
	
	//2c
	@Query("select sum(TOT_WRITE_OFF_AMT) + sum(COLLECTIVE_PROVISION_AMT) +sum(SPECIFIC_PROVISION_AMT) from CR10 where STD_PRODUCT_TYPE_CD = 'BOND'")
	Double DebtAllowances();
		
	//2d
	@Query("select sum(SPECIFIC_PROVISION_AMT) from CR10 where STD_PRODUCT_TYPE_CD = 'BOND' ")
	Double DebtAllocatedSpecific();
		
	//2e
	@Query("select sum(TOT_WRITE_OFF_AMT) + sum(COLLECTIVE_PROVISION_AMT) +sum(OTH_PROVISION_AMT) from CR10 where STD_PRODUCT_TYPE_CD = 'BOND'")
	Double DebtAllocatedGeneral();
	
	//3a
	@Query("select sum(EOP_BALANCE_AMT) from CR10 where ACCT_PASTDUE_FLAG = 'Y' and( STD_PRODUCT_TYPE_CD = 'LC' or STD_PRODUCT_TYPE_CD = 'GUAR' or STD_PRODUCT_TYPE_CD = 'COMM')")
	Double OffBalanceDefaultedExposure();
	
	//3b
	@Query("select sum(EOP_BALANCE_AMT) from CR10 where ACCT_PASTDUE_FLAG = 'N' and( STD_PRODUCT_TYPE_CD = 'LC' or STD_PRODUCT_TYPE_CD = 'GUAR' or STD_PRODUCT_TYPE_CD = 'COMM')")
	Double OffBalanceNotDefaultedExposure();
	
	//3c
	@Query("select sum(TOT_WRITE_OFF_AMT + COLLECTIVE_PROVISION_AMT + SPECIFIC_PROVISION_AMT + OTH_PROVISION_AMT) from CR10 where STD_PRODUCT_TYPE_CD = 'LC' or STD_PRODUCT_TYPE_CD = 'GUAR' or STD_PRODUCT_TYPE_CD = 'COMM'")
	Double OffBalanceAllowances();
	
	//3d
	@Query("select sum(SPECIFIC_PROVISION_AMT) from CR10 where STD_PRODUCT_TYPE_CD = 'LC' or STD_PRODUCT_TYPE_CD = 'GUAR' or STD_PRODUCT_TYPE_CD = 'COMM'")
	Double OffBalanceAllocatedSpecific();
	
	//3e
	@Query("select sum(TOT_WRITE_OFF_AMT + COLLECTIVE_PROVISION_AMT +  OTH_PROVISION_AMT) from CR10 where STD_PRODUCT_TYPE_CD = 'LC' or STD_PRODUCT_TYPE_CD = 'GUAR' or STD_PRODUCT_TYPE_CD = 'COMM'")
	Double OffBalanceAllocatedGeneral();
	
	//CR2
	//13d
	@Query("select sum(DEF_EXP_PAST_PRD) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME' or STD_PRODUCT_TYPE_CD = 'BOND')")
	Double DefaultedExpenditurePrevPeriod();
	
	//14d
	@Query("select sum(DEF_EXP_CUR_PRD) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME' or STD_PRODUCT_TYPE_CD = 'BOND')")
	Double DefaultedExpenditureCurPeriod();
	
	//15d
	@Query("select sum(EOP_BALANCE_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME' or STD_PRODUCT_TYPE_CD = 'BOND') and RET_TO_NDEFAULT_DT > LST_REP_DT")
	Double RetToNonDefaulted();
	
	//16d
	@Query("select sum(TOT_WRITE_OFF_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME' or STD_PRODUCT_TYPE_CD = 'BOND')")
	Double AmountWriteOff();
	
	//17d
	@Query("select sum(OTH_PROVISION_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME' or STD_PRODUCT_TYPE_CD = 'BOND')")
	Double OtherChanges();
	
	//CR3
	//14d
	@Query("select sum(UNSECURED_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME')")
	Double LoansExposuresUnsecured();
	
	//14e
	@Query("select sum(SECURED_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME')")
	Double LoansExposuresSecured();
	
	//14f
	@Query("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='COLLATERALS') and (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME')")
	Double LoansExposuresSecuredCollateral();
	
	
	//14g
	@Query ("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='FINANCIAL GUARANTEES') and (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME')")
	Double LoansExposuresSecuredFinancialGuarantees();
	
	
	//14h
	@Query ("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='CREDIT DERIVATIVES') and (STD_PRODUCT_TYPE_CD = 'LOAN' or STD_PRODUCT_TYPE_CD = 'RME')")
	Double LoansExposuresSecuredCreditDerivatives();
	
	//15d 
	@Query ("select sum(UNSECURED_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'BOND')")
	Double DebtSecuritiesExposuresUnsecured();
	
	//15e
	@Query ("select sum(SECURED_AMT) from CR10 where (STD_PRODUCT_TYPE_CD = 'BOND')")
	Double DebtSecuritiesExposuresSecured();
	
	//15f
	@Query ("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='COLLATERALS') and (STD_PRODUCT_TYPE_CD = 'BOND')")
	Double DebtSecuritiesExposuresSecuredCollateral();
	
	//15g
	@Query ("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='FINANCIAL GUARANTEES') and (STD_PRODUCT_TYPE_CD = 'BOND')")
	Double DebtSecuritiesExposuresSecuredFinancialGuarantees();
	
	//15h
	@Query ("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='CREDIT DERIVATIVES') and (STD_PRODUCT_TYPE_CD = 'BOND')")
	Double DebtSecuritiesExposuresSecuredCreditDerivatives();
	
	//17d
	@Query ("select sum(UNSECURED_AMT) from CR10 where (ACCT_PASTDUE_FLAG='Y')")
	Double OfDefaultedExposuresUnsecured();
	
	//17e
	@Query ("select sum(SECURED_AMT) from CR10 where (ACCT_PASTDUE_FLAG='Y')")
	Double OfDefaultedExposuresSecured();
	
	//17f
	@Query ("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='COLLATERALS') and (ACCT_PASTDUE_FLAG='Y')")
	Double OfDefaultedExposuresSecuredCollaterals();
	
	
	//17g
	@Query ("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='FINANCIAL GUARANTEES') and (ACCT_PASTDUE_FLAG='Y')")
	Double OfDefaultedExposuresSecuredFinancialGuarantees();
	
	//17h
	@Query ("select sum(SECURED_AMT) from CR10 where (CRM_TYPE='CREDIT DERIVATIVES') and (ACCT_PASTDUE_FLAG='Y')")
	Double OfDefaultedExposuresSecuredCreditDerivatives();
	
	//CR5
	@Query("select sum (POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT<0) and (BASEL_EXPOSURE_CLASS_CD= 'SOV')")
	Double Sovereigs0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV') and (POST_CRM_RISK_WEIGHT<10)")
	Double Sovereigs10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV') and (POST_CRM_RISK_WEIGHT<20)")
	Double Sovereigs20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV') and (POST_CRM_RISK_WEIGHT<35)")
	Double Sovereigs35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV') and (POST_CRM_RISK_WEIGHT<50)")
	Double Sovereigs50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV') and (POST_CRM_RISK_WEIGHT<75)")
	Double Sovereigs75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV') and (POST_CRM_RISK_WEIGHT<100)")
	Double Sovereigs100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV') and (POST_CRM_RISK_WEIGHT<150)")
	Double Sovereigs150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double SovereigsOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SOV')")
	Double SovereigsTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT<0)")
	Double NonCentralGov0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT<10)")
	Double NonCentralGov10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT<20)")
	Double NonCentralGov20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT<35)")
	Double NonCentralGov35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT<50)")
	Double NonCentralGov50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT<75)")
	Double NonCentralGov75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT<100)")
	Double NonCentralGov100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT<150)")
	Double NonCentralGov150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double NonCentralGovOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='PSE')")
	Double NonCentralGovTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT<0)")
	Double MultilateralDevBanks0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT<10)")
	Double MultilateralDevBanks10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT<20)")
	Double MultilateralDevBanks20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT<35)")
	Double MultilateralDevBanks35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT<50)")
	Double MultilateralDevBanks50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT<75)")
	Double MultilateralDevBanks75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT<100)")
	Double MultilateralDevBanks100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT<150)")
	Double MultilateralDevBanks150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double MultilateralDevBanksOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='MDB')")
	Double MultilateralDevBanksTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT<0)")
	Double Banks0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT<10)")
	Double Banks10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT<20)")
	Double Banks20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT<35)")
	Double Banks35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT<50)")
	Double Banks50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT<75)")
	Double Banks75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT<100)")
	Double Banks100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT<150)")
	Double Banks150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double BanksOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='Bank')")
	Double BanksTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT<0)")
	Double SecurityFirms0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT<10)")
	Double SecurityFirms10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT<20)")
	Double SecurityFirms20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT<35)")
	Double SecurityFirms35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT<50)")
	Double SecurityFirms50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT<75)")
	Double SecurityFirms75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT<100)")
	Double SecurityFirms100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT<150)")
	Double SecurityFirms150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double SecurityFirmsOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS')")
	Double SecurityFirmsTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT<0)")
	Double Corporates0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT<10)")
	Double Corporates10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT<20)")
	Double Corporates20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT<35)")
	Double Corporates35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT<50)")
	Double Corporates50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT<75)")
	Double Corporates75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT<100)")
	Double Corporates100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT<150)")
	Double Corporates150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double CorporatesOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CORP')")
	Double CorporatesTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT<0)")
	Double RegulatoryRetailPortfolio0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT<10)")
	Double RegulatoryRetailPortfolio10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT<20)")
	Double RegulatoryRetailPortfolio20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT<35)")
	Double RegulatoryRetailPortfolio35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT<50)")
	Double RegulatoryRetailPortfolio50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT<75)")
	Double RegulatoryRetailPortfolio75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT<100)")
	Double RegulatoryRetailPortfolio100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT<150)")
	Double RegulatoryRetailPortfolio150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double RegulatoryRetailPortfolioOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RET')")
	Double RegulatoryRetailPortfolioTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT<0)")
	Double SecByResidentialProperty0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT<10)")
	Double SecByResidentialProperty10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT<20)")
	Double SecByResidentialProperty20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT<35)")
	Double SecByResidentialProperty35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT<50)")
	Double SecByResidentialProperty50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT<75)")
	Double SecByResidentialProperty75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT<100)")
	Double SecByResidentialProperty100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT<150)")
	Double SecByResidentialProperty150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double SecByResidentialPropertyOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='RRE')")
	Double SecByResidentialPropertyTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT<0)")
	Double SecByCommercialRealEstate0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT<10)")
	Double SecByCommercialRealEstate10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT<20)")
	Double SecByCommercialRealEstate20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT<35)")
	Double SecByCommercialRealEstate35();

	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT<50)")
	Double SecByCommercialRealEstate50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT<75)")
	Double SecByCommercialRealEstate75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT<100)")
	Double SecByCommercialRealEstate100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT<150)")
	Double SecByCommercialRealEstate150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double SecByCommercialRealEstateOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='CRE')")
	Double SecByCommercialRealEstateTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT<0)")
	Double Equity0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT<10)")
	Double Equity10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT<20)")
	Double Equity20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT<35)")
	Double Equity35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT<50)")
	Double Equity50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT<75)")
	Double Equity75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT<100)")
	Double Equity100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT<150)")
	Double Equity150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double EquityOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='EQUITY')")
	Double EquityTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT<0)")
	Double PastDueLoans0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT<10)")
	Double PastDueLoans10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT<20)")
	Double PastDueLoans20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT<35)")
	Double PastDueLoans35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT<50)")
	Double PastDueLoans50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT<75)")
	Double PastDueLoans75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT<100)")
	Double PastDueLoans100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT<150)")
	Double PastDueLoans150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT) and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double PastDueLoansOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT)")
	Double PastDueLoansTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT<0)")
	Double HigherRisk0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT<10)")
	Double HigherRisk10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT<20)")
	Double HigherRisk20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT<35)")
	Double HigherRisk35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT<50)")
	Double HigherRisk50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT<75)")
	Double HigherRisk75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT<100)")
	Double HigherRisk100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT<150)")
	Double HigherRisk150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50) and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double HigherRiskOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (POST_CRM_RISK_WEIGHT=1.50)")
	Double HigherRiskTotal();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT<0)")
	Double OtherAssets0();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT<10)")
	Double OtherAssets10();
	
	@Query("select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT<20)")
	Double OtherAssets20();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT<35)")
	Double OtherAssets35();
	
	@Query("select 0.25*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT<50)")
	Double OtherAssets50();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT<75)")
	Double OtherAssets75();
	
	@Query("select 0.15*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT<100)")
	Double OtherAssets100();
	
	@Query("select 0.10*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT<150)")
	Double OtherAssets150();
	
	@Query(value="select 0.05*sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS') and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double OtherAssetsOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS')")
	Double OtherAssetsTotal();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT<0)")
	Double Total0();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT<10)")
	Double Total10();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT<20)")
	Double Total20();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT<35)")
	Double Total35();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT<50)")
	Double Total50();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT<75)")
	Double Total75();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT<100)")
	Double Total100();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT<150)")
	Double Total150();
	
	@Query(value="select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' ) and (POST_CRM_RISK_WEIGHT not in (POST_CRM_RISK_WEIGHT<0,POST_CRM_RISK_WEIGHT<10,POST_CRM_RISK_WEIGHT<20,POST_CRM_RISK_WEIGHT<35,POST_CRM_RISK_WEIGHT<50,POST_CRM_RISK_WEIGHT<75,POST_CRM_RISK_WEIGHT<100,POST_CRM_RISK_WEIGHT<150))",nativeQuery=true)
	Double TotalOthers();
	
	@Query("select sum(POST_CCF_CRM_EXPOSURE_AMT) from CR10 where (DEF_EXP_CUR_PRD<=0.10*EOP_BALANCE_AMT OR POST_CRM_RISK_WEIGHT = 1.50 OR BASEL_EXPOSURE_CLASS_CD='SOP' OR BASEL_EXPOSURE_CLASS_CD='PSE' OR BASEL_EXPOSURE_CLASS_CD='MDB' OR BASEL_EXPOSURE_CLASS_CD='Bank' OR BASEL_EXPOSURE_CLASS_CD='SEC_FIRMS' OR BASEL_EXPOSURE_CLASS_CD='CORP' OR BASEL_EXPOSURE_CLASS_CD='RET' OR BASEL_EXPOSURE_CLASS_CD='RRE' OR BASEL_EXPOSURE_CLASS_CD='CRE' OR BASEL_EXPOSURE_CLASS_CD='EQUITY' OR BASEL_EXPOSURE_CLASS_CD='OTHER ASSETS' )")
	Double Total_Tot();

	
	
}
